### PR TITLE
Add Laravel package base

### PR DESCRIPTION
**Pull request by TENIOS**
I was inspired by your repository and wanted developers to use it. So I've added a small base to create a package for you to upload to [Packagist](https://packagist.org/). That way it can be used by other developers just by installing your package and getting the configs in Japanese using the `config-jp:publish` command.

Sorry.

### CODE REVIEW

**Comment by TENIOS** [comment]
Review @maru0914.

**Review by maru0914 — APPROVED** [review]

**Comment by maru0914** [comment]
@TENIOS 
Wow, thanks so much! 
I’ll definitely find time to work on implementing this command.

**Comment by TENIOS** [comment]
@maru0914, please can you give me an email address to contact me?

**Comment by maru0914** [comment]
@TENIOS 

> @maru0914, please can you give me an email address to contact me?

Sure, please contact me at the following email address:
marudev0914@gmail.com

**Comment by TENIOS** [comment]
@maru0914, Thank you.

Delete your message or mention of your email address to avoid spam.

**Pull request merged**
